Add docker
ros-industrial-consortium/snp_automate_2022 pull request #4
Opened 2024-03-06 20:20 UTC by Yolnan

2024-03-06 20:24 UTC, Yolnan commented
@marip8 When entering the snp_automate_2022 container, I get notified that "groups: cannot find name for group ID ..." and my username is "I have no name!". I made sure to set the CURRENT_UID environment variable.

Do we want to to add a user to the Dockerfile?  It currently seems to be root.

2024-03-06 23:25 UTC, marip8 commented
> @marip8 When entering the snp_automate_2022 container, I get notified that "groups: cannot find name for group ID ..." and my username is "I have no name!". I made sure to set the CURRENT_UID environment variable.

Is your machine get your user name from the domain? One of mine does and I get the same error; my other machine is not on a domain and I don't run into this issue. In any case, this issue shouldn't prevent your from running anything

2024-03-06 23:28 UTC, marip8 requested changes

2024-03-06 23:28 UTC, marip8 commented on .github/workflows/docker.yml
> +      - '.github/workflows/docker.yml'
Remove
```suggestion
```

2024-03-06 23:28 UTC, marip8 commented on .github/workflows/docker.yml
> +            TAG=${{ matrix.distro }}-0.21
The SNP docker images only have the suffix `-master` at the moment, no version numbers

```suggestion
            TAG=${{ matrix.distro }}-master
```

2024-03-06 23:28 UTC, marip8 commented on docker/Dockerfile
> +  && source /opt/snp/install/setup.bash \
Let's also install some useful utilities like `sudo` for the image

```suggestion
# Run apt update and install useful utilities like sudo
RUN apt update -y -qq && apt install -y -qq sudo

# Bind mount the source directory so as not to unnecessarily copy source code into the docker image
ARG WORKSPACE_DIR=/opt/snp_automate_2022
RUN --mount=type=bind,target=${WORKSPACE_DIR}/src/snp_automate_2022 \
  && source /opt/snp/install/setup.bash \
```

2024-03-07 18:30 UTC, Yolnan commented
> > @marip8 When entering the snp_automate_2022 container, I get notified that "groups: cannot find name for group ID ..." and my username is "I have no name!". I made sure to set the CURRENT_UID environment variable.
> 
> Is your machine get your user name from the domain? One of mine does and I get the same error; my other machine is not on a domain and I don't run into this issue. In any case, this issue shouldn't prevent your from running anything
> 
> FWIW, mounting the directories below let's the docker image know where your user name and password information can be found
> 
> ```
>       - /etc/passwd:/etc/passwd:ro
>       - /etc/group:/etc/group:ro
> ```

I think my laptop is. I did test the container and it seems to work despite the username. I have those directories in the docker compose.yml. Oddly, I think Tyler recommended that I remove them.

2024-03-09 01:20 UTC, marip8 requested changes

2024-03-09 01:20 UTC, marip8 commented on docker/Dockerfile
> +RUN python3 -m pip install open3d pyquaternion --upgrade
Remove; comes from SNP docker image now

2024-03-09 01:20 UTC, marip8 commented on docker/Dockerfile
> +    --skip-keys libvtk
```suggestion
    -iry
```

2024-03-09 01:20 UTC, marip8 commented on docker/README.md
> +docker pull ghcr.io/ros-industrial-consortium/scan_n_plan_workshop:<tag>
```suggestion
docker pull ghcr.io/ros-industrial-consortium/snp_automate_2022:<tag>
```

2024-03-09 01:20 UTC, marip8 commented on docker/docker-compose.yml
> +      ROS_LOG_DIR: /tmp
```suggestion
      ROS_LOG_DIR: /tmp
      ROS_LOCALHOST_ONLY=1
```

2024-03-09 01:20 UTC, marip8 commented on docker/docker-compose.yml
> +      - /etc/group:/etc/group:ro
Add `/dev` for USB devices

```suggestion
      - /etc/group:/etc/group:ro
      - /dev:/dev
```

2024-03-09 01:20 UTC, marip8 commented on docker/docker-compose.yml
> +              capabilities: [gpu]
Add the ROS1 bridge

```suggestion
              capabilities: [gpu]
    # ROS1 bridge
    ros1-bridge:
    environment:
      ROS_LOG_DIR: /tmp
      ROS_LOCAL_HOST_ONLY: 1
    container_name: ros1-bridge
    image: ghcr.io/ros-industrial/ros1_bridge:noetic-foxy
    tty: true
    privileged: true
    network_mode: host
```

2024-03-12 15:27 UTC, marip8 approved these changes

2024-03-12 15:27 UTC, merged